### ISSUE TITLE
KODE ERROR BRO !

### ISSUE THREAD

**Issue by e1337-eth** [KANG-NEWBIE/PyCompile#3]
Kode Lu masih ada yang Error,
1. Dibagian Kondisi yang paling bawah ( if ask == '1' :)
2. Input untuk py() ( a = input ("bla bla bla") )

Pembenaran : 
1. if ask == 1 :
2. a = raw_input("bla bla bla")

Thanks

~wahyu.py
Team = Security Darknet
Find Us on Instagram : security_darknet
:-)

**Comment by R3DB0T** [comment]
Baru tau python3 support raw_input
